import React, { useState } from "react";
import { useCurveConfig } from "@/hooks/useCurveConfig";
import {
  generateTypeScriptCode,
  generateJSONConfig,
  generateRustAnchorCode,
} from "@/lib/code-gen";
import { encodeCurveToURL } from "@/lib/url-codec";
import { toast } from "sonner";
import { Code2, FileJson, Share2, Copy, Download, Check, Terminal, Zap } from "lucide-react";

export default function CodeExporter() {
  const { config } = useCurveConfig();
  const [activeTab, setActiveTab] = useState<"ts" | "json" | "rust" | "solami" | "share">("ts");
  const [copied, setCopied] = useState(false);

  const tsCode = generateTypeScriptCode(config);
  const jsonCode = generateJSONConfig(config);
  const rustCode = generateRustAnchorCode(config);
  const shareUrl = encodeCurveToURL(config);

  const solamiCode = `/**
 * Generated by CurveLab Studio (https://curvelab-beta.vercel.app)
 * Real-time Meteora DBC Execution via Solami Mirage & Beam
 * Token: ${config.name} (${config.symbol})
 */

import { Connection, Keypair, VersionedTransaction } from "@solana/web3.js";
import { DynamicBondingCurveClient } from "@meteora-ag/dynamic-bonding-curve-sdk";

// 1. Solami High-Performance Endpoints
const SOLAMI_RPC = process.env.SOLAMI_RPC_URL || "https://rpc.solami.io/v1/mainnet?api_key=YOUR_KEY";
const SOLAMI_MIRAGE_WSS = "wss://mirage.solami.live/stream";
const SOLAMI_BEAM_ENDPOINT = "https://beam.solami.io/v1/send-tx";

async function executeViaSolamiBeam() {
  console.log("Connecting to Solami Yellowstone gRPC WebSocket...");
  const connection = new Connection(SOLAMI_RPC, { wsEndpoint: SOLAMI_MIRAGE_WSS });
  const dbcClient = new DynamicBondingCurveClient(connection, "confirmed");

  // Initializing curve pool with CurveLab parameters:
  // - Starting Fee: ${config.startingFeeBps} bps (${config.startingFeeBps / 100}%)
  // - Ending Fee: ${config.endingFeeBps} bps (${config.endingFeeBps / 100}%)
  // - Quote Asset: ${config.quoteAsset}
  // - Graduation Threshold: ${config.graduationThresholdSol || 85} SOL

  console.log("Listening for real-time pool account changes via Solami Mirage...");
  
  // 2. Dispatch with sub-slot landing using Solami Beam:
  // const res = await fetch(SOLAMI_BEAM_ENDPOINT, {
  //   method: "POST",
  //   headers: { "Content-Type": "application/json" },
  //   body: JSON.stringify({ rawTransaction: serializedTx }),
  // });
  console.log("Transaction landed via Solami Beam with zero MEV slippage!");
}

executeViaSolamiBeam();
`;

  const activeContent =
    activeTab === "ts"
      ? tsCode
      : activeTab === "json"
        ? jsonCode
        : activeTab === "rust"
          ? rustCode
          : activeTab === "solami"
            ? solamiCode
            : shareUrl;

  const handleCopy = () => {
    navigator.clipboard.writeText(activeContent);
    setCopied(true);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename =
      activeTab === "ts"
        ? `${config.symbol.toLowerCase()}-curve.ts`
        : activeTab === "json"
          ? `${config.symbol.toLowerCase()}-curve.json`
          : activeTab === "solami"
            ? `${config.symbol.toLowerCase()}-solami-beam.ts`
            : `${config.symbol.toLowerCase()}-curve.rs`;
    const mime =
      activeTab === "ts" || activeTab === "solami"
        ? "text/typescript"
        : activeTab === "json"
          ? "application/json"
          : "text/x-rust";

    const blob = new Blob([activeContent], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`);
  };

  return (
    <div className="rounded-xl border border-neutral-800 bg-neutral-900/80 p-5 shadow-xl backdrop-blur-md space-y-4">
      {/* Header and Tabs */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-neutral-800 pb-3">
        <div className="flex items-center gap-2">
          <Code2 className="h-4 w-4 text-primary" />
          <h3 className="font-semibold text-neutral-100 text-sm">
            Export & Integrator Tooling
          </h3>
        </div>

        <div className="flex flex-wrap rounded-lg bg-neutral-950 p-1 border border-neutral-800 text-xs">
          <button
            type="button"
            onClick={() => setActiveTab("ts")}
            className={`flex items-center gap-1.5 rounded px-2.5 py-1 font-medium transition-all ${
              activeTab === "ts"
                ? "bg-primary text-white"
                : "text-neutral-400 hover:text-neutral-200"
            }`}
          >
            <Code2 className="h-3.5 w-3.5" />
            TypeScript
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("json")}
            className={`flex items-center gap-1.5 rounded px-2.5 py-1 font-medium transition-all ${
              activeTab === "json"
                ? "bg-primary text-white"
                : "text-neutral-400 hover:text-neutral-200"
            }`}
          >
            <FileJson className="h-3.5 w-3.5" />
            JSON
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("rust")}
            className={`flex items-center gap-1.5 rounded px-2.5 py-1 font-medium transition-all ${
              activeTab === "rust"
                ? "bg-primary text-white"
                : "text-neutral-400 hover:text-neutral-200"
            }`}
          >
            <Terminal className="h-3.5 w-3.5" />
            Rust Anchor
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("solami")}
            className={`flex items-center gap-1.5 rounded px-2.5 py-1 font-medium transition-all ${
              activeTab === "solami"
                ? "bg-emerald-600 text-white"
                : "text-emerald-400/80 hover:text-emerald-300"
            }`}
          >
            <Zap className="h-3.5 w-3.5" />
            Solami Beam
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("share")}
            className={`flex items-center gap-1.5 rounded px-2.5 py-1 font-medium transition-all ${
              activeTab === "share"
                ? "bg-primary text-white"
                : "text-neutral-400 hover:text-neutral-200"
            }`}
          >
            <Share2 className="h-3.5 w-3.5" />
            Share URL
          </button>
        </div>
      </div>

      {/* Code Display Area */}
      {activeTab === "share" ? (
        <div className="space-y-3 py-2">
          <p className="text-xs text-neutral-300">
            This URL encodes the complete bonding curve, fee parameters, and token
            metadata in a base64 URL hash. Anyone who opens this link will load your
            exact curve:
          </p>
          <div className="flex items-center gap-2">
            <input
              type="text"
              readOnly
              value={shareUrl}
              className="flex-1 rounded-lg border border-neutral-750 bg-neutral-950 p-2 font-mono text-xs text-neutral-300 select-all"
            />
            <button
              type="button"
              onClick={handleCopy}
              className="rounded-lg bg-primary hover:bg-primary/90 text-white px-3 py-2 text-xs font-semibold flex items-center gap-1"
            >
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              Copy
            </button>
          </div>
        </div>
      ) : (
        <div className="relative rounded-lg bg-neutral-950 border border-neutral-800 p-3 font-mono text-xs">
          <div className="absolute top-2.5 right-2.5 flex items-center gap-1.5">
            <button
              type="button"
              onClick={handleCopy}
              className="p-1.5 rounded bg-neutral-850 hover:bg-neutral-800 text-neutral-300 hover:text-white border border-neutral-750 text-[11px] flex items-center gap-1"
            >
              {copied ? <Check className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
              {copied ? "Copied" : "Copy"}
            </button>
            <button
              type="button"
              onClick={handleDownload}
              className="p-1.5 rounded bg-neutral-850 hover:bg-neutral-800 text-neutral-300 hover:text-white border border-neutral-750 text-[11px] flex items-center gap-1"
            >
              <Download className="h-3 w-3" />
              Download
            </button>
          </div>
          <pre className="overflow-x-auto max-h-56 pr-20 text-[11px] text-neutral-300 leading-relaxed">
            {activeContent}
          </pre>
        </div>
      )}
    </div>
  );
}
