import { CurveLabConfig } from "@/types/curve-config";

/**
 * Generates an end-to-end, runnable TypeScript script for Meteora DBC.
 */
export function generateTypeScriptCode(cfg: CurveLabConfig): string {
  const feeModeSdk =
    cfg.feeMode === "ExponentialDecay"
      ? "BaseFeeMode.FeeSchedulerExponential"
      : "BaseFeeMode.FeeSchedulerLinear";

  return `/**
 * Generated by CurveLab 🧪 (Meteora Dynamic Bonding Curve Studio)
 * Token: \${cfg.name} (\${cfg.symbol})
 * Architecture: Meteora DBC -> DAMM v2 Migration
 */

import { Connection, Keypair, PublicKey, sendAndConfirmTransaction } from "@solana/web3.js";
import { NATIVE_MINT } from "@solana/spl-token";
import {
  DynamicBondingCurveClient,
  buildCurveWithCustomSqrtPrices,
  getSqrtPriceFromPrice,
  deriveDbcPoolAddress,
  ActivationType,
  BaseFeeMode,
  CollectFeeMode,
  DammV2BaseFeeMode,
  DammV2DynamicFeeMode,
  MigratedCollectFeeMode,
  MigrationFeeOption,
  MigrationOption,
  TokenAuthorityOption,
  TokenType,
  SwapMode,
} from "@meteora-ag/dynamic-bonding-curve-sdk";
import BN from "bn.js";

async function main() {
  // 1. Initialize Solana Connection & DBC Client
  const rpcUrl = process.env.SOLANA_RPC_URL || "https://api.devnet.solana.com";
  const connection = new Connection(rpcUrl, "confirmed");
  const client = new DynamicBondingCurveClient(connection, "confirmed");

  // Load Deployer Keypair (e.g., from local file or env)
  // const payer = Keypair.fromSecretKey(...);
  console.log("Connected to RPC:", rpcUrl);

  // 2. Build SqrtPrices for Curve Segments
  const tokenBaseDecimal = ${cfg.tokenDecimals};
  const tokenQuoteDecimal = ${cfg.quoteAsset === "WSOL" ? 9 : 6}; // ${cfg.quoteAsset} decimals
  const priceCheckpoints = ${JSON.stringify(cfg.sqrtPriceCheckpoints, null, 2)};
  
  const sqrtPrices = priceCheckpoints.map((p) =>
    getSqrtPriceFromPrice(String(p), tokenBaseDecimal, tokenQuoteDecimal)
  );

  // 3. Construct CurveLab Config Parameters
  const curveConfig = buildCurveWithCustomSqrtPrices({
    token: {
      tokenType: ${cfg.tokenType === "SPL" ? "TokenType.SPLToken" : "TokenType.Token2022"},
      tokenBaseDecimal,
      tokenQuoteDecimal,
      tokenAuthorityOption: TokenAuthorityOption.PartnerUpdateAuthority,
      totalTokenSupply: ${cfg.totalSupply},
      leftover: 1000,
    },
    fee: {
      baseFeeParams: {
        baseFeeMode: ${feeModeSdk},
        feeSchedulerParam: {
          startingFeeBps: ${cfg.startingFeeBps},
          endingFeeBps: ${cfg.endingFeeBps},
          numberOfPeriod: ${cfg.feeMode === "Fixed" ? 0 : cfg.numberOfPeriods},
          totalDuration: ${cfg.feeMode === "Fixed" ? 0 : cfg.totalDurationSeconds},
        },
      },
      dynamicFeeEnabled: ${cfg.dynamicFeeEnabled},
      collectFeeMode: CollectFeeMode.QuoteToken,
      creatorTradingFeePercentage: 0,
      poolCreationFee: 0,
      enableFirstSwapWithMinFee: false,
    },
    migration: {
      migrationOption: MigrationOption.MET_DAMM_V2,
      migrationFeeOption: MigrationFeeOption.Customizable,
      migrationFee: {
        feePercentage: ${cfg.migrationFeePercentage},
        creatorFeePercentage: ${cfg.creatorMigrationFeePercentage},
      },
      migratedPoolFee: {
        collectFeeMode: MigratedCollectFeeMode.QuoteToken,
        dynamicFee: DammV2DynamicFeeMode.Enabled,
        poolFeeBps: ${cfg.migratedPoolFeeBps},
        baseFeeMode: DammV2BaseFeeMode.FeeTimeSchedulerLinear,
      },
    },
    liquidityDistribution: {
      partnerLiquidityPercentage: ${Math.max(0, 100 - cfg.partnerPermanentLockPercentage - cfg.creatorPermanentLockPercentage)},
      partnerPermanentLockedLiquidityPercentage: ${cfg.partnerPermanentLockPercentage},
      creatorLiquidityPercentage: 0,
      creatorPermanentLockedLiquidityPercentage: ${cfg.creatorPermanentLockPercentage},
    },
    lockedVesting: {
      totalLockedVestingAmount: 0,
      numberOfVestingPeriod: 0,
      cliffUnlockAmount: 0,
      totalVestingDuration: 0,
      cliffDurationFromMigrationTime: 0,
    },
    activationType: ActivationType.Timestamp,
    sqrtPrices,
    liquidityWeights: ${JSON.stringify(cfg.liquidityWeights)},
  });

  console.log("Curve configuration validated successfully!");

  /*
  // 4. Create Config on Devnet / Mainnet
  const configKeypair = Keypair.generate();
  const createConfigTx = await client.partner.createConfig({
    config: configKeypair.publicKey,
    quoteMint: ${
      cfg.quoteAsset === "WSOL"
        ? "NATIVE_MINT"
        : cfg.quoteAsset === "USDC"
          ? 'new PublicKey("EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v") // Mainnet USDC (or devnet equivalent)'
          : 'new PublicKey("USDG111111111111111111111111111111111111111") // USDG Global Dollar'
    },
    feeClaimer: payer.publicKey,
    leftoverReceiver: payer.publicKey,
    payer: payer.publicKey,
    ...curveConfig,
  });
  await sendAndConfirmTransaction(connection, createConfigTx, [payer, configKeypair]);
  console.log("Config created:", configKeypair.publicKey.toBase58());

  // 5. Launch Pool on Top of Config
  const baseMint = Keypair.generate();
  const createPoolTx = await client.creator.createPool({
    config: configKeypair.publicKey,
    baseMint: baseMint.publicKey,
    name: "${cfg.name}",
    symbol: "${cfg.symbol}",
    uri: "https://curvelab.app/metadata.json",
    payer: payer.publicKey,
    poolCreator: payer.publicKey,
  });
  await sendAndConfirmTransaction(connection, createPoolTx, [payer, baseMint]);
  const poolAddress = deriveDbcPoolAddress(NATIVE_MINT, baseMint.publicKey, configKeypair.publicKey);
  console.log("Pool launched:", poolAddress.toBase58());
  */
}

main().catch(console.error);
`;
}

/**
 * Generates JSON configuration matching Meteora Invent DBC schema.
 */
export function generateJSONConfig(cfg: CurveLabConfig): string {
  const feeMode =
    cfg.feeMode === "Fixed"
      ? 0
      : cfg.feeMode === "LinearDecay"
        ? 1
        : 2;

  const exportPayload = {
    generator: "CurveLab Studio",
    version: "1.0.0",
    token: {
      name: cfg.name,
      symbol: cfg.symbol,
      totalSupply: cfg.totalSupply,
      decimals: cfg.tokenDecimals,
      tokenType: cfg.tokenType,
    },
    curve: {
      buildCurveMode: 5, // buildCurveWithCustomSqrtPrices
      segments: cfg.segments,
      prices: cfg.sqrtPriceCheckpoints,
      liquidityWeights: cfg.liquidityWeights,
      graduationThresholdSol: cfg.graduationThresholdSol,
    },
    fee: {
      feeMode,
      startingFeeBps: cfg.startingFeeBps,
      endingFeeBps: cfg.endingFeeBps,
      numberOfPeriods: cfg.numberOfPeriods,
      totalDurationSeconds: cfg.totalDurationSeconds,
      dynamicFeeEnabled: cfg.dynamicFeeEnabled,
    },
    migration: {
      option: "MET_DAMM_V2",
      feePercentage: cfg.migrationFeePercentage,
      creatorSplitPercentage: cfg.creatorMigrationFeePercentage,
      partnerPermanentLockPercentage: cfg.partnerPermanentLockPercentage,
      creatorPermanentLockPercentage: cfg.creatorPermanentLockPercentage,
      migratedPoolFeeBps: cfg.migratedPoolFeeBps,
    },
  };

  return JSON.stringify(exportPayload, null, 2);
}

/**
 * Generates ready-to-compile Rust / Anchor struct snippet for Meteora DBC program CPI.
 */
export function generateRustAnchorCode(cfg: CurveLabConfig): string {
  const feeModeRust =
    cfg.feeMode === "Fixed"
      ? "BaseFeeMode::FeeSchedulerLinear"
      : cfg.feeMode === "ExponentialDecay"
        ? "BaseFeeMode::FeeSchedulerExponential"
        : "BaseFeeMode::FeeSchedulerLinear";

  return `//! Generated by CurveLab 🧪 (Meteora DBC Rust Anchor Initializer)
//! Token: ${cfg.name} (${cfg.symbol})
//! Architecture: Meteora Dynamic Bonding Curve -> DAMM v2

use anchor_lang::prelude::*;
use dynamic_bonding_curve::{
    cpi::accounts::CreateConfig,
    state::{BaseFeeMode, FeeSchedulerParam, MigrationOption, CollectFeeMode},
    program::DynamicBondingCurve,
};

pub fn initialize_curvelab_config(ctx: Context<InitializeDbcConfig>) -> Result<()> {
    // 1. Fee Scheduler Parameter
    let _base_fee_mode = ${feeModeRust};
    let fee_scheduler_param = FeeSchedulerParam {
        starting_fee_bps: ${cfg.startingFeeBps},
        ending_fee_bps: ${cfg.endingFeeBps},
        number_of_period: ${cfg.feeMode === "Fixed" ? 0 : cfg.numberOfPeriods},
        total_duration: ${cfg.feeMode === "Fixed" ? 0 : cfg.totalDurationSeconds},
    };

    // 2. Liquidity Distribution (Guaranteed 100% Total)
    let partner_permanent_lock: u8 = ${cfg.partnerPermanentLockPercentage};
    let creator_permanent_lock: u8 = ${cfg.creatorPermanentLockPercentage};
    let partner_unlocked: u8 = 100 - partner_permanent_lock - creator_permanent_lock;

    msg!("CurveLab: Initializing Meteora DBC Config for ${cfg.symbol}");
    msg!("Partner Lock: {}%, Creator Lock: {}%, Partner Unlocked: {}%", 
        partner_permanent_lock, creator_permanent_lock, partner_unlocked);
    
    // 3. CPI Invocation to Meteora DBC Program
    // dynamic_bonding_curve::cpi::create_config(cpi_ctx, config_params)?;

    Ok(())
}
`;
}

